### ISSUE TITLE
Let's split the glob notebook into 2 

### ISSUE THREAD

**Issue by granrothge** [neutrons/IPythonNotebookTutorial#1]
Let's split the Glob note book into 2
1)  A notebook where you load 1 file and do all the examples of various types of plotting
1)  A notebook where we add the file looping.

**Comment by ricleal** [comment]
Done. @yxqd do you mind doing  the `for` looping? [3 - Multiple plots - Glob.ipynb](https://github.com/neutrons/IPythonNotebookTutorial/blob/master/3%20-%20Multiple%20plots%20-%20Glob.ipynb)
I think in this one we want to introduce more advanced plot options including `axis` manipulation.
